[package]
name = "rutel_derive"
version = "0.3.1"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
proc-macro2 = "0.4"
